// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDadHcDIkqCHfAuQpivW3YrqSgsSYS_PkQ',
    appId: '1:151412764105:web:ffcbe70c3f256433660c18',
    messagingSenderId: '151412764105',
    projectId: 'grofood-385a9',
    authDomain: 'grofood-385a9.firebaseapp.com',
    storageBucket: 'grofood-385a9.firebasestorage.app',
    measurementId: 'G-JZDMM3GZQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8wAix4r6fq-KB5hNK-TyYbbcfQvOFNmQ',
    appId: '1:151412764105:android:73f449318081f989660c18',
    messagingSenderId: '151412764105',
    projectId: 'grofood-385a9',
    storageBucket: 'grofood-385a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw5uv8m6XH3tXdhJvH9vzay5haImhMv4M',
    appId: '1:151412764105:ios:f6c3731dc46370b4660c18',
    messagingSenderId: '151412764105',
    projectId: 'grofood-385a9',
    storageBucket: 'grofood-385a9.firebasestorage.app',
    iosBundleId: 'com.example.khujoApp',
  );
}
